# Generated by Django 2.2.4 on 2019-10-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100, verbose_name='nome_cliente')),
                ('email', models.CharField(max_length=200, unique=True, verbose_name='E-mail')),
                ('lista_pedidos', models.CharField(max_length=500, verbose_name='pedidos')),
                ('forma_de_pagamento',models.CharField(max_length=100, verbose_name='forma_de_pagamento')),
                ('endereco', models.CharField(max_length=2000, verbose_name='endereço')),
                ('contato_numero', models.PositiveIntegerField(verbose_name='contato')),
            ],
            options={
                'ordering': ('lista_pedidos',),
            },
        ),
    ]
