# Generated by Django 2.2.4 on 2019-10-18 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos',
            old_name='contato_numero',
            new_name='numero_contato',
        ),
    ]
