# Generated by Django 2.2.4 on 2019-10-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20191018_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='numero_contato',
            field=models.CharField(max_length=12, verbose_name='contato'),
        ),
    ]
